[global]
disable = ["MD013", "MD034"]
extend-enable = ["MD060"]
flavor = "gfm"

[per-file-flavor]
"**/*.mdx" = "mdx"

[MD025]
front-matter-title = ""

[MD033]
allowed-elements = ["details", "summary"]

[MD046]
style = "fenced"

[MD060]
style = "compact"
