import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  guidesSidebar: [{ type: "autogenerated", dirName: "guides" }],
  referenceSidebar: [{ type: "autogenerated", dirName: "reference" }],
  developmentSidebar: [{ type: "autogenerated", dirName: "development" }],
};

export default sidebars;
